services:
  # BACKEND
  backend:
    build: ./backend
    container_name: autoflow_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    # CAMBIO: Leemos el archivo .env de la carpeta backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo_db

  # FRONTEND
  frontend:
    build: ./frontend
    container_name: autoflow_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # CAMBIO: Leemos el archivo .env de la carpeta frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    stdin_open: true
    tty: true

  # MONGO DB
  mongo_db:
    image: mongo:latest
    container_name: autoflow_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: